###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= Quadrotor

COMMON_OBJS = Control.o Pid.o Accelerometer.o Gyros.o Motors.o a2d_10.o Delay.o Timer.o UART.o Hardware.o

include ../Rules.mk

